development:
  adapter: postgresql
  database: pmr_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: pmr_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: pmr_production
  pool: 5
  timeout: 5000
